In [ ]:
import gymnasium as gym
import evogym.envs
from evogym import sample_robot
import numpy as np
from evogym import get_full_connectivity


if __name__ == '__main__':

    body = np.array([
    [0, 2, 3, 3, 2, 0],
    [1, 3, 3, 3, 3, 1],
    [4, 4, 2, 2, 4, 4],
    [3, 3, 0, 0, 3, 3],
        [2, 2, 0, 0, 2, 2],
        [0, 0, 0, 0, 0, 0]
    ])

    env = gym.make('Walker-v0', body=body, render_mode='human')
    env.reset()
    i=0
    while True:
        action = env.action_space.sample()
        ob, reward, terminated, truncated, info = env.step(action)

        if terminated or truncated:
            env.reset()
        print(body)

    env.close()

[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
[[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]

In [7]:
from stable_baselines3.common.env_util import make_vec_env

In [3]:
pip install google-generativeai --upgrade

Note: you may need to restart the kernel to use updated packages.


In [3]:
import evogym
evogym.VOXEL_TYPES

{'EMPTY': 0, 'RIGID': 1, 'SOFT': 2, 'H_ACT': 3, 'V_ACT': 4, 'FIXED': 5}

In [77]:
Replies=[]

In [79]:
Replies=[]
for i in range(100):
    try:
        # Your function call
        GenEnvs(Replies)
    except Exception as e:
        # Print the error and skip to next iteration
        print(f"Error at iteration {i+1}: {e}")
        continue

# Base output folder
base_dir = "levels"
os.makedirs(base_dir, exist_ok=True)

for idx, Reply in enumerate(Replies):
    folder_path = os.path.join(base_dir, 'env'+str(idx+1))
    os.makedirs(folder_path, exist_ok=True)

    for difficulty, level_data in Reply.items():
        file_path = os.path.join(folder_path, f"{difficulty}.json")
        with open(file_path, "w") as f:
            json.dump(level_data, f, indent=4)

print("✅ Levels saved into numbered folders with easy/medium/hard.json files")

Running: ['C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python', 'C:\\Users\\numam\\EALLMs\\gemini_runner.py', 'running superfast']
Running: ['C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python', 'C:\\Users\\numam\\EALLMs\\gemini_runner.py', 'running superfast']
Error at iteration 1: Expecting value: line 1 column 54116 (char 54115)
Running: ['C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python', 'C:\\Users\\numam\\EALLMs\\gemini_runner.py', 'running superfast']
Running: ['C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python', 'C:\\Users\\numam\\EALLMs\\gemini_runner.py', 'running superfast']
Running: ['C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python', 'C:\\Users\\numam\\EALLMs\\gemini_runner.py', 'running superfast']
Running: ['C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python', 'C:\\Users\\numam\\EALLMs\\gemini_runner.py', 'running superfast']
Running: ['C:\\Users\\numam\

In [76]:
import subprocess
import json
import os
def GenEnvs(Replies):
    def call_gemini(prompt):
        script_path = os.path.join(os.getcwd(), "gemini_runner.py")
    
        print("Running:",         ["C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python", script_path, prompt],)
    
        result = subprocess.run(
            ["C:\\Users\\numam\\AppData\\Local\\Programs\\Python\\Python310\\python", script_path, prompt],
            capture_output=True,
            text=True
        )
    
        return repr(result.stdout)
        print("STDERR:", result.stderr)
    
        try:
            return json.loads(result.stdout)["response"]
        except json.JSONDecodeError:
            print("Failed to parse JSON from script output.")
            return None
    
    reply = call_gemini("running superfast")
    
    jso = json.loads(reply[8:].replace('\\n','').replace('\\n','')[:-4].replace('        ','').replace('      ',''))
    Replies.append(jso)
print("Reply:", jso)
with open("NewEnv.json", "w") as f:
    json.dump(jso, f)


Reply: {'easy': {'grid_width': 50, 'grid_height': 20, 'objects': {'ground': {'indices': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49], 'types': [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], 'neighbors': {'0': [1, 50, 51], '1': [0, 2, 50, 51, 52], '2': [1, 3, 51, 52, 53], '3': [2, 4, 52, 53, 54], '4': [3, 5, 53, 54, 55], '5': [4, 6, 54, 55, 56], '6': [5, 7, 55, 56, 57], '7': [6, 8, 56, 57, 58], '8': [7, 9, 57, 58, 59], '9': [8, 10, 58, 59, 60], '10': [9, 11, 59, 60, 61], '11': [10, 12, 60, 61, 62], '12': [11, 13, 61, 62, 63], '13': [12, 14, 62, 63, 64], '14': [13, 15, 63, 64, 65], '15': [14, 16, 64, 65, 66], '16': [15, 17, 65, 66, 67], '17': [16, 18, 66, 67, 68], '18': [17, 19, 67, 68, 69], '19': [18, 20, 68, 69, 70], '20': [19, 21, 69, 70,

In [74]:
jso['hard']

{'grid_width': 50,
 'grid_height': 20,
 'objects': {'ground': {'indices': [0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49],
   'types': [5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5,
    5],
   'neighbors': {'0': [1, 50, 51],
    '1': [0, 2, 50, 51, 52],
    '2': [1, 3, 51, 52, 53],
    '3': [2, 4, 52, 53, 54],
    '4': [3, 5, 53, 54, 55],
    '5': [4, 6, 54, 55, 56]

In [64]:
from evogym import EvoWorld, EvoSim, EvoViewer, sample_robot, WorldObject
import os
import numpy as np

# create a EvoWorld object with environment data and visualize it

world = EvoWorld.from_json(os.path.join( 'NewEnv.json'))
# world = EvoWorld.from_json(json_reply)
world.pretty_print()
print('world print')

# add a randomly sampled 5x5 robot to the world

body = np.array([
    [0, 2, 3, 3, 2, 0],
    [1, 3, 3, 3, 3, 1],
    [4, 4, 2, 2, 4, 4],
    [3, 3, 0, 0, 3, 3],
        [2, 2, 0, 0, 2, 2],
        [0, 0, 0, 0, 0, 0]
    ])
print('body defined\n', body)
robot_structure, robot_connections = sample_robot((5, 5))
robo = WorldObject.from_array(name='robot',structure=body)
print('empty robo', robo)
robo.set_pos(4,5)
print('initialized ',robo)
world.add_object(robo)
print('adding obj')
world.pretty_print()

# create a simulation using our world object

sim = EvoSim(world)
sim.reset()
print('sim.reset')
# a viewer object will allow us to visualize our simulation

viewer = EvoViewer(sim)
viewer.track_objects('robot')

# we put it all together in this loop in which we sample a random action for our simulation, step the simulation, and render it

for i in range(500):

    sim.set_action(x,
        'robot', 
        np.random.uniform(
            low = 0.6,
            high = 1.6,
            size=(sim.get_dim_action_space('robot'),))
        )
    sim.step()
    viewer.render('screen')


3 | . . . . . . . . . . . . . . . . . . . . . . . S H H S . . . . . . . . . . . . . . . . . . . . . . . 
2 | . . . . . . . . . . . . . . . . . . . . . . . V S S V . . . . . . . . . . . . . . . . . . . . . . . 
1 | . . . . . . . . . . . . . . . . . . . . . . . S H H S . . . . . . . . . . . . . . . . . . . . . . . 
0 | F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F F 
   -----------------------------------------------------------------------------------------------------
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 
world print
body defined
 [[0 2 3 3 2 0]
 [1 3 3 3 3 1]
 [4 4 2 2 4 4]
 [3 3 0 0 3 3]
 [2 2 0 0 2 2]
 [0 0 0 0 0 0]]
empty robo Size (6, 6) object named robot at (0, 0).
initialized  Size (6, 6) object named robot at (4, 5).
adding obj

0 | . . . . . S H H S . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
9 | . . . . R H H H H R . .

NameError: name 'x' is not defined

In [51]:
import os
json_File_Path = os.path.join(r'C:\Users\numam\evogym\evogym-design-tool\exported', 'fixedvoxel.json')
print('path =', json_File_Path)


import json

# Open and read a JSON file
with open(json_File_Path, "r") as file:
    data = json.load(file)

print("Contents of JSON file:")
print(data)


Help on method add_object in module evogym.world:

add_object(obj: 'WorldObject') -> 'None' method of evogym.world.EvoWorld instance
     Add a single object to the world.
    
    Args:
        obj (WorldObject): object to add.

